name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: mahmaduzair/django-app:latest
    
    
    # - name: Run Docker container
    #   run: |
    #     docker run -d -p 8000:8000 mahmaduzair/django-app:latest



# name: Build and Push Docker Image

# on:
#   push:
#     branches:
#       - main  # Adjust this branch name as needed

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

#       # - name: Build and tag the Docker image
#       #   run: |
#       #     docker build -t your-docker-username/your-image-name .
#       #     docker tag your-docker-username/your-image-name your-docker-username/your-image-name:latest

#       # - name: Push the Docker image to Docker Hub
#       #   run: docker push mahmaduzair/django-app:latest
#        - name: Build and push Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         push: true
#         tags: usamakenway/easy-llm-server:latest
